/*
 * exo-scripts.js — Exchange Online script generator for the Group Administration tool.
 *
 * Pure string building: no DOM, no network, no ITTools dependency. Loadable in node
 * for verification (see docs/superpowers/plans/2026-08-28-group-admin-expansion-v2.md).
 *
 * TEMPLATE ESCAPING RULES (violating these silently corrupts generated scripts):
 *   - Never emit PowerShell ${var} syntax — "${" interpolates in JS template literals.
 *   - Write "\\" for every literal backslash (a lone "\" eats the next character).
 *   - Never emit PowerShell backticks: no line continuations, no `n. One line per cmdlet.
 *   - Every injected value goes through psStr().
 */
(function (root) {
  "use strict";

  // ── Low-level helpers ─────────────────────────────────────────
  /** Single-quoted PowerShell string literal, with '' doubling. */
  function psStr(value) {
    return "'" + String(value == null ? "" : value).replace(/'/g, "''") + "'";
  }

  /** Filename-safe slug for output names. */
  function slug(value) {
    const s = String(value == null ? "" : value)
      .replace(/[^A-Za-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40);
    return s || "target";
  }

  /** Normalise to CRLF so the .ps1 and .bat behave on Windows. */
  function crlf(text) {
    return String(text).replace(/\r?\n/g, "\r\n");
  }

  // ── Operation labels + output filenames ───────────────────────
  const OP_LABELS = {
    members:     { add: "Add members", remove: "Remove members", export: "Export members" },
    permissions: { grant: "Grant access", remove: "Remove access", export: "Export access list" },
  };

  const SCRIPT_BASE = {
    "distribution-list": {
      add:    "Add-DistributionListMembers",
      remove: "Remove-DistributionListMembers",
      export: "Export-DistributionListMembers",
    },
    "mail-security-group": {
      add:    "Add-MailSecurityGroupMembers",
      remove: "Remove-MailSecurityGroupMembers",
      export: "Export-MailSecurityGroupMembers",
    },
    "shared-mailbox": {
      grant:  "Grant-SharedMailboxAccess",
      remove: "Remove-SharedMailboxAccess",
      export: "Export-SharedMailboxAccess",
    },
  };

  function isMailbox(typeId) { return typeId === "shared-mailbox"; }

  /**
   * buildContext({ typeId, typeLabel, op, target, targetDisplay, identities,
   *                perms:{full,sendAs,onBehalf}, autoMapping, tech }) -> ctx
   */
  function buildContext(input) {
    const typeId = input.typeId;
    const op     = input.op;
    const model  = isMailbox(typeId) ? "permissions" : "members";
    const base   = (SCRIPT_BASE[typeId] || {})[op];
    if (!base) throw new Error("Unsupported object type / operation: " + typeId + " / " + op);

    const now     = new Date();
    const target  = String(input.target || "").trim();
    const display = input.targetDisplay || target;
    const label   = input.typeLabel || typeId;
    const opLabel = OP_LABELS[model][op];

    return {
      typeId: typeId,
      op: op,
      model: model,
      opLabel: opLabel,
      typeLabel: label,
      title: label + ": " + opLabel.toLowerCase(),
      target: target,
      targetDisplay: display,
      targetSlug: slug(display),
      identities: (input.identities || []).slice(),
      perms: {
        full:     !!(input.perms && input.perms.full),
        sendAs:   !!(input.perms && input.perms.sendAs),
        onBehalf: !!(input.perms && input.perms.onBehalf),
      },
      autoMapping: input.autoMapping !== false,
      tech: input.tech || "unknown",
      timestamp: now.toISOString().replace("T", " ").slice(0, 19) + " UTC",
      dateOnly: now.toISOString().slice(0, 10),
      scriptName: base + ".ps1",
      batName: "Run-" + base + ".bat",
      zipName: base + "-" + slug(display) + "-" + now.toISOString().slice(0, 10) + ".zip",
      logBase: base,
    };
  }

  // ── Shared script blocks ──────────────────────────────────────
  /** Header comment + error preference + logging helpers + transcript start. */
  function psPrologue(ctx, extraHeaderLines) {
    const header = [
      "#  Object type : " + ctx.typeLabel,
      "#  Target      : " + ctx.targetDisplay + " <" + ctx.target + ">",
      "#  Operation   : " + ctx.opLabel,
    ]
      .concat(extraHeaderLines || [])
      .concat([
        "#  Generated   : " + ctx.timestamp,
        "#  Generated by: " + ctx.tech,
      ])
      .join("\n");

    const readOnly = ctx.op === "export";
    const steps = readOnly
      ? [
          "#    1. Connects to Exchange Online in your own admin context.",
          "#    2. Starts a transcript next to this script for audit.",
          "#    3. Reads the current state and writes a CSV next to this script.",
          "#    Nothing is changed. This script only reads.",
        ]
      : [
          "#    1. Connects to Exchange Online in your own admin context.",
          "#    2. Starts a transcript next to this script for audit.",
          "#    3. Runs every change with -WhatIf first, so nothing changes yet.",
          "#    4. Waits for you to type YES, then applies the changes for real.",
        ];

    return `# =====================================================================
#  ${ctx.title}
#  Generated by IT Tools Hub, Group Administration
# ---------------------------------------------------------------------
${header}
# ---------------------------------------------------------------------
#  What this does:
${steps.join("\n")}
# =====================================================================

$ErrorActionPreference = "Continue"

function Write-Head { param([string]$Message) Write-Host ""; Write-Host "  $Message" -ForegroundColor Cyan }
function Write-Item { param([string]$Message, [string]$Color = "Gray") Write-Host "    $Message" -ForegroundColor $Color }

$stamp      = Get-Date -Format 'yyyyMMdd-HHmmss'
$transcript = Join-Path $PSScriptRoot (${psStr(ctx.logBase)} + "-" + $stamp + ".log")
Start-Transcript -Path $transcript | Out-Null
`;
  }

  /** ExchangeOnlineManagement install guard + Connect-ExchangeOnline. */
  function psConnect() {
    return `
# --- Connect to Exchange Online ------------------------------------
Write-Head "Connecting to Exchange Online..."

$minVersion = [Version]"3.9.0"
$installed  = Get-Module -ListAvailable -Name ExchangeOnlineManagement | Sort-Object Version -Descending | Select-Object -First 1
if ($null -eq $installed -or $installed.Version -lt $minVersion) {
    Write-Item "ExchangeOnlineManagement 3.9.0 or newer not found. Installing for the current user..." Yellow
    try {
        Install-Module ExchangeOnlineManagement -MinimumVersion $minVersion -Force -AllowClobber -Scope CurrentUser -ErrorAction Stop
    } catch {
        Write-Item ("ERROR: Could not install ExchangeOnlineManagement. " + $_.Exception.Message) Red
        Write-Item "Install it manually, then re-run: Install-Module ExchangeOnlineManagement -Scope CurrentUser -Force" Yellow
        Stop-Transcript | Out-Null
        exit 1
    }
}

try {
    Import-Module ExchangeOnlineManagement -MinimumVersion $minVersion -ErrorAction Stop
    Connect-ExchangeOnline -ShowBanner:$false -ErrorAction Stop
    Write-Item "Connected." Green
} catch {
    Write-Item ("ERROR: Could not connect to Exchange Online. " + $_.Exception.Message) Red
    Stop-Transcript | Out-Null
    exit 1
}
`;
  }

  /** Summary tail, disconnect, transcript stop. extraSummary is raw PowerShell lines. */
  function psEpilogue(ctx, extraSummary) {
    return `
# --- Finish --------------------------------------------------------
Write-Head "Complete"
${extraSummary || ""}Write-Item ("Transcript: " + $transcript)
Write-Host ""

Disconnect-ExchangeOnline -Confirm:$false -ErrorAction SilentlyContinue
Stop-Transcript | Out-Null
`;
  }

  // ── Distribution list / mail-enabled security group ───────────
  function buildGroupMemberScript(ctx) {
    const memberBlock = ctx.identities.length
      ? "$Members = @(\n" + ctx.identities.map(v => "    " + psStr(v)).join(",\n") + "\n)"
      : "$Members = @()";

    const inputs = `
# --- Inputs -------------------------------------------------------
$Target = ${psStr(ctx.target)}
${memberBlock}
`;

    const verify = `
# --- Verify the target --------------------------------------------
Write-Head "Verifying the target in Exchange Online..."
try {
    $group = Get-DistributionGroup -Identity $Target -ErrorAction Stop
    Write-Item ("Found: " + $group.DisplayName + " <" + $group.PrimarySmtpAddress + "> [" + $group.RecipientTypeDetails + "]") Green
} catch {
    Write-Item ("ERROR: Could not find '$Target' in Exchange Online. " + $_.Exception.Message) Red
    Disconnect-ExchangeOnline -Confirm:$false -ErrorAction SilentlyContinue
    Stop-Transcript | Out-Null
    exit 1
}
`;
    // Export is read-only: no dry run, no confirmation gate, writes a CSV next to the script.
    if (ctx.op === "export") {
      const exportBody = `
# --- Export members -----------------------------------------------
Write-Head "Reading current members..."
$outFile = Join-Path $PSScriptRoot (${psStr(ctx.logBase + "-" + ctx.targetSlug)} + "-" + $stamp + ".csv")
$count = 0
try {
    $members = Get-DistributionGroupMember -Identity $Target -ResultSize Unlimited -ErrorAction Stop
    $count = @($members).Count
    if ($count -eq 0) {
        Write-Item "This group has no members. No CSV was written." Yellow
    } else {
        $members | Select-Object DisplayName, PrimarySmtpAddress, RecipientTypeDetails, Alias | Export-Csv -Path $outFile -NoTypeInformation -Encoding UTF8
        Write-Item ("Exported " + $count + " members to:") Green
        Write-Item $outFile
    }
} catch {
    Write-Item ("ERROR: Could not read members. " + $_.Exception.Message) Red
}
`;
      return psPrologue(ctx, []) + inputs + psConnect() + verify + exportBody +
             psEpilogue(ctx, 'Write-Item ("Members read: " + $count)\n');
    }

    const isAdd     = ctx.op === "add";
    const cmdlet    = isAdd ? "Add-DistributionGroupMember" : "Remove-DistributionGroupMember";
    const liveArgs  = isAdd ? "-BypassSecurityGroupManagerCheck" : "-BypassSecurityGroupManagerCheck -Confirm:$false";
    const wouldWord = isAdd ? "WOULD ADD" : "WOULD REMOVE";
    const didWord   = isAdd ? "ADDED" : "REMOVED";

    const body = `
# --- Dry run (-WhatIf, nothing changes) ---------------------------
Write-Head "Dry run. Showing what would change. No changes are made yet."
foreach ($m in $Members) {
    try {
        ${cmdlet} -Identity $Target -Member $m ${liveArgs} -WhatIf -ErrorAction Stop
        Write-Item ("${wouldWord}: " + $m) Yellow
    } catch {
        Write-Item ("WOULD FAIL: " + $m + " - " + $_.Exception.Message) Red
    }
}

# --- Confirm ------------------------------------------------------
Write-Host ""
$answer = Read-Host "  Type YES to apply these changes for real (anything else aborts)"
if ($answer -ne "YES") {
    Write-Item "Aborted. No changes were made." Yellow
    Disconnect-ExchangeOnline -Confirm:$false -ErrorAction SilentlyContinue
    Stop-Transcript | Out-Null
    exit 0
}

# --- Live run -----------------------------------------------------
Write-Head "Applying changes..."
$ok = 0
$failed = 0
foreach ($m in $Members) {
    try {
        ${cmdlet} -Identity $Target -Member $m ${liveArgs} -ErrorAction Stop
        Write-Item ("${didWord}: " + $m) Green
        $ok++
    } catch {
        Write-Item ("FAILED: " + $m + " - " + $_.Exception.Message) Red
        $failed++
    }
}
`;

    const summary = 'Write-Item ("Succeeded : " + $ok)\nWrite-Item ("Failed    : " + $failed)\n';

    return psPrologue(ctx, ["#  Members     : " + ctx.identities.length]) +
           inputs + psConnect() + verify + body + psEpilogue(ctx, summary);
  }

  /** Dispatch on object type. */
  function buildScript(ctx) {
    if (ctx.typeId === "distribution-list" || ctx.typeId === "mail-security-group") {
      return crlf(buildGroupMemberScript(ctx));
    }
    throw new Error("Script generation is not implemented for object type: " + ctx.typeId);
  }

  root.ExoScripts = {
    buildContext: buildContext,
    buildScript: buildScript,
    _psStr: psStr,
    _slug: slug,
    _crlf: crlf,
    _psPrologue: psPrologue,
    _psConnect: psConnect,
    _psEpilogue: psEpilogue,
  };
})(typeof window !== "undefined" ? window : globalThis);
